### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pdesantis** [chrisguttandin/extendable-media-recorder#242]
This project looks super interesting!

I'm trying to create a MediaRecorder that will output a .wav file. It sounds like this library, combined with https://github.com/chrisguttandin/extendable-media-recorder-wav-encoder, can do that? Any hints on how to go about that?

Thanks!
Pat

**Comment by chrisguttandin** [comment]
Hi Pat,

thanks for discovering this project. And sorry for not documenting it so far. It's on my todo list but I haven't had time to do it yet. It's quite complex and this is why I didn't want to do it in a rush.

If you don't want to wait for met to write it all down, it might help to take a look at the [integration tests](https://github.com/chrisguttandin/extendable-media-recorder/blob/014f922a7eb2be6f4feaa78e7b6f5bd97181a772/test/integration/module.js). There is one test which is doing exactly what you want.

The basic idea behind this project is to provide a library/module which implements the exact same API as the native MediaRecorder. It should also leverage the native MediaRecorder under the hood when asked to record something in a format the system has a codec for. But on top of that it should be extendable. Which means it should be possible to provide a custom codec. The only encoder I implemented so far is the wav encoder as you already found out.

I hope this helps a bit. Please, let me know if you get it working or if you have any questions. I try to write more detailed documentation as soon as possible.

**Comment by pdesantis** [comment]
Awesome, thanks for the pointer! I'll give that a try and report back!

**Comment by pdesantis** [comment]
This is going great, thanks again for this project!

I have one issue with the event types. When implementing an event listener in TypeScript, I get the following error: `Property 'data' does not exist on type Event` on [this line](https://github.com/chrisguttandin/extendable-media-recorder/blob/014f922a7eb2be6f4feaa78e7b6f5bd97181a772/test/integration/module.js#L44):
```javascript
mediaRecorder.addEventListener('dataavailable', async ({ data }) => {
```

Do you have any suggestions on how to fix this? For now I'm just ignoring the error.

**Comment by chrisguttandin** [comment]
The reason is relatively simple. I haven't defined the events yet in a way that TypeScript can understand it. I fixed that now. Version v4.1.0 contains the proper type definitions for the `dataavailable` event.

**Comment by guest271314** [comment]
@chrisguttandin 

> The basic idea behind this project is to provide a library/module which implements the exact same API as the native MediaRecorder.

FYI There are open and closed issues for native MediaRecorder that could be avoided, specifically relevant to capturing a `MediaStream` from an `HTMLMediaElement` (e.g., `<video>`, `<audio>`) the specification states that `MediaRecorder` should stop recording when a `MediaStreamTrack` is added or removed from the `MediaStream`; see 

- https://github.com/w3c/mediacapture-record/issues/4
- https://github.com/w3c/mediacapture-record/issues/147
- https://github.com/w3c/mediacapture-record/issues/167

**Comment by chrisguttandin** [comment]
Hi @pdesantis, I finally added some documentation. Sorry for the long delay.

**Comment by pdesantis** [comment]
Awesome! It looks great!
