### ISSUE TITLE
How to record multiple audio input devices

### ISSUE THREAD

**Issue by pdesantis** [chrisguttandin/extendable-media-recorder#257]
Hello,

I'm trying to record audio from multiple microphones at the same time, as separate tracks in a file. Is that possible to do using a single MediaRecorder instance? Or am I supposed to create a new MediaRecorder for each device?

I tried using a single MediaRecorder using the code below, but it only seemed to record audio from the first input device.

```javascript
const deviceIds = devices.map((device) => device.deviceId);
const constraints = {
    audio: {
        deviceId: deviceIds,
    },
};
const stream = await navigator.mediaDevices.getUserMedia(constraints);
const recorder = new MediaRecorder(stream, {
    mimeType: 'audio/wav',
});
```

When I used multiple instances, it worked just fine.

**Comment by chrisguttandin** [comment]
Hi @pdesantis,

I think `getUserMedia()` can't be used liked that. If you pass an array as the `deviceId` constraint it essentially means: "Please give me a mediaStream from any of those devices."

What you could try instead is to call `getUserMedia()` for each device you want to record. Then you could pipe all streams through an `AudioContext` to combine them. And then you can get a `mediaStream` again by using a `MediaStreamAudioDestinationNode`. That `mediaStream` can now be used with a `MediaRecorder`.

**Comment by pdesantis** [comment]
Ah, that makes sense, thank you!
