### ISSUE TITLE
Does extendable-media-recorder provide the capability to set the track order within resulting file?

### ISSUE THREAD

**Issue by guest271314** [chrisguttandin/extendable-media-recorder#352]
Media Capture and Streams does not require track order at resulting file

https://www.w3.org/TR/mediacapture-streams/

> The tracks of a MediaStream are stored in a track set. The track set MUST contain the MediaStreamTrack objects that correspond to the tracks of the stream. The relative order of the tracks in the set is User Agent defined and the API will never put any requirements on the order.

See https://github.com/w3c/mediacapture-record/issues/179.

Does extendable-media-recorder provide the capability to set the track order within resulting file?

**Comment by chrisguttandin** [comment]
Hi @guest271314,

it took me a while to understand what you are asking for and what the use case is that you have in mind. :-) But after reading the issue that you referenced and the issues referenced from there I can understand why this would be useful.

However the purpose of this project is to allow people to extend the MediaRecorder with custom codecs while leaving the built-in codecs untouched. If we would add the possibility to specify the track order (for example with a setTrackOrder() function as you proposed) that would result in a feature gap between the natively implemented codecs (which don't support it) and the custom codecs (which could support it).

Also this project is not really feature complete and does only support custom audio codecs up to now. Adding a feature to order video tracks in relation to audio tracks would be like doing step 2 before step 1.

I hope this all makes sense to you. Please feel free to reopen this issue in case I got anything wrong.

**Comment by guest271314** [comment]
> that would result in a feature gap between the natively implemented codecs (which don't support it)

The particular codec used whether supported by the browser or extended are not the issue. Writing the tracks to the container in a consistent order is the use case. 

> However the purpose of this project is to allow people to extend the MediaRecorder with custom codecs

Filed this issue due to the initial consideration that this repository had the purpose of writing the complete code for and implementing `MediaRecorder` specification from scratch.
