### ISSUE TITLE
Extendable Recorder : AddEventListender callback for datavailable as parent class method.

### ISSUE THREAD

**Issue by ishwara-bhat** [chrisguttandin/extendable-media-recorder#472]
Hi,
The "datavailable" event handler works with addEventListener. 
 this.mediaRecorder.addEventListener("dataavailable", (event) => {
                    console.log("callbackfn: data vailable");
                    console.log(event.data);
                    this.myprocessingfunction(event.data);
                });
                
But I am having trouble with passing 'this'  context to the callback. Hence                     this.myprocessingfunction(event.data) does not work. It is not the package issue, but I have trouble getting event for the ondatavailable interface.

As I studied online, passing this has few ways. https://stackoverflow.com/questions/20627138/typescript-this-scoping-issue-when-called-in-jquery-callback.
I am trying the first one where I define function in my "outer class". 

...
    public onDataAvailable = (event: any) => {
        console.log("on data available");
        this.myprocessingfunction(event.data);
    }
...
I'm assigning this to 
recorder.ondataavailable = this.onDataAvailable ;

This interface does not work. It does not give error. But the event does not fire either.

Kindly let me know how to make event listener work with parent class so that I could invoke complex processing as class method.

Thanks for the help.

Regards
Ishwar

**Comment by chrisguttandin** [comment]
Hi @ishwara-bhat,

you're right the `ondataavailable` property doesn't work yet. I haven't implemented that so far.

In the meantime I think it will work if you use the `addEventListener()` method like this: `recorder.addEventListener('dataavailable', this.onDataAvailable)`.

Please let me know if it works.

**Comment by chrisguttandin** [comment]
Hi @ishwara-bhat, it is now (since v5.1.0) possible to assign an event handler to the `ondataavailable` property as well as using the `addEventListener()` method.

That should solve your problem. Please let me know if you run into any other issues.
