### ISSUE TITLE
Duration is zero

### ISSUE THREAD

**Issue by assada** [chrisguttandin/extendable-media-recorder#636]
```javascript
let stream = audioCtx.createMediaStreamDestination();
// ...play some audio to stream...
let recorder = new MediaRecorder(stream);
recorder.start();
recorder.addEventListener('dataavailable', function (e) {
    saveBlob(e.data, 'sample.wav');
});
```

Result: playable as normal media file but with 0 duration
![image](https://user-images.githubusercontent.com/1472664/104791674-3e83a500-57a4-11eb-8839-0a999b3ab700.png)

Its posible to get ogg/wav format instead webm?

**Comment by assada** [comment]
Haha! I forgot to add `{ mimeType: 'audio/wav' }` option to media recorder! After that its works awesome!

sorry for the hasty issue...

**Comment by chrisguttandin** [comment]
No problem. I'm glad you got it working.
