### ISSUE TITLE
Uncaught (in promise) Error: There was no instance of an encoder stored with the given id.

### ISSUE THREAD

**Issue by FrenchMajesty** [chrisguttandin/extendable-media-recorder#640]
Hello,

I get this error whenever I attempt to start a recording for the 2nd time. 
```
module.ts:49 Uncaught (in promise) Error: There was no instance of an encoder stored with the given id.
    at Worker.<anonymous> (module.ts:49)
```
On first run it goes all as expected and works well. However, when I try to start a 2nd recording it fails.

Here is my `AudioRecorder` class which is what I use to capture audio: 

![image](https://user-images.githubusercontent.com/24761660/112711018-5b6ae180-8e93-11eb-8f36-2d2550fd5197.png)

Here is the logic from the React component:

![image](https://user-images.githubusercontent.com/24761660/112711136-1b582e80-8e94-11eb-895c-c2df8dcedd14.png)

**Comment by chrisguttandin** [comment]
Hi @FrenchMajesty, thanks for making me aware of this. I think this is just an oversight on my end. The MediaRecorder is currently implemented in a way which only allows it to be used once. As a quick fix you could recreate a new MediaRecorder whenever start() is called.

**Comment by FrenchMajesty** [comment]
@chrisguttandin I attempted to use your quick fix of just re-creating a new `MediaRecorder` everytime i need to record, however my app still crashes with the following error:

> Unhandled Rejection (Error): Another request was made to initiate an encoding.

**Comment by chrisguttandin** [comment]
I believe the issue is fixed now. I added some tests which check that a MediaRecorder can be used twice and fixed the errors that caused those tests to fail. The update is up on npm as v6.1.54.

Please let me know if you still experience any issues.
