### ISSUE TITLE
Error: The sampleRate is not defined.

### ISSUE THREAD

**Issue by tomtobac** [chrisguttandin/extendable-media-recorder#655]
Hello 👋  

First of all, thank your time into this library.

I am trying to use the `MediaRecorder` with a custom encoder `audio/wav` with multiple audio tracks. On their parent track I am registering the new encoder like this:

```tsx
useEffect(() => {
  const onInit = async () => {
    if (!MediaRecorder.isTypeSupported("audio/wav")) {
      await register(await connect());
    }
    console.log("Encoder registred");
  };
  onInit();
}, []);
```

But whenever a new child/audio tracks tries to create a new instance of `MediaRecorder` it throws an Uncaught error: The sampleRate is not defined. Any ideas?

This are my dependencies:
```
    "extendable-media-recorder": "^6.5.10",
    "extendable-media-recorder-wav-encoder": "^7.0.62",
```

**Comment by tomtobac** [comment]
Here is how I use the `MediaRecorder` inside of each `AudioTrack`

```tsx
const mst = track.mediaStreamTrack; // AudioTrack
const stream = new MediaStream();
stream.addTrack(mst);

const mediaRecorder = new MediaRecorder(stream, {
  mimeType: "audio/wav",
});

mediaRecorder.ondataavailable = (e)  => mysocket.emit("stream", e.buffer);

mediaRecorder.start(1000);
```

**Comment by chrisguttandin** [comment]
Hi @tomtobac,

I guess you're using Chrome and the error originates from here: https://github.com/chrisguttandin/extendable-media-recorder/blob/148a769a9bab5613ddc0baaa6ae46d0050a820f4/src/factories/webm-pcm-media-recorder.ts#L95

This happens if the the settings of the audio track don't contain the sampleRate information. Could you please check what `mst.getSettings()` returns in your case?

**Comment by tomtobac** [comment]
Hey @chrisguttandin , thank you for the quick reply.

Yes, both of them are defined.

```tsx
console.group(`Track ${track.sid}`);
console.log(`SampleSize of mst: ${mst.getSettings().sampleSize}`);
console.log(`SampleSize of stream: ${stream.getAudioTracks()[0].getSettings().sampleSize}`);
console.groupEnd();
```

Output:
```
Track MT0de8b7e70f049a756ee9d79d30b943a0
  SampleSize of mst: 16
  SampleSize of stream: 16
```

**Comment by tomtobac** [comment]
I guess at the beginning it doesn't have this properties my `AudioTrack` so I need to check if the `sampleRate` property exist before to initialize the `MediaRecorder`. I am kinda newbie in the world of media... I am wondering if there is any way to observe or react base on the this property.

**Comment by chrisguttandin** [comment]
Interesting, is this a `MediaStreamTrack` that comes from a peer connection?

**Comment by jsoto-gladia** [comment]
Hello. Yes it is.
when I first print the settings of the MediaStreamTrack I get:
`{deviceId: '1f706ccd-473a-48f4-81db-76448bbb6998', sampleSize: 16}`
the following ones I get:
`{channelCount: 1, deviceId: '1f706ccd-473a-48f4-81db-76448bbb6998', latency: 0.01, sampleRate: 48000, sampleSize: 16}`

**Comment by chrisguttandin** [comment]
If I understand this correctly the library should probably wait (with a timeout) until the `sampleRate` is defined. That seems to be what @tomtobac is doing anyway. It's also what fixed the problem for you, @jsoto-gladia, right?

**Comment by jsoto-gladia** [comment]
yes

**Comment by chrisguttandin** [comment]
I moved the code that reads the `sampleRate` by calling `getSettings()` into the `start()` method. This does at least ensure it get's called at a later point in time.

Please feel free to reopen this issue in case the problem persists.
