### ISSUE TITLE
How to specify sample and bit rates for the recording?

### ISSUE THREAD

**Issue by abhijeet-toptal** [chrisguttandin/extendable-media-recorder#659]
Is there a way I can specify the following while recording:

Channels: 1
Sample Rate: 16000
Precision: 16-bit
Bit Rate: 256k
Sample Encoding: 16-bit Signed Integer PCM

I have seen the recordings done via native MediaRecorder have got a single channel and less sample and bit rates.

**Comment by abhijeet-toptal** [comment]
@chrisguttandin can you please check this?

**Comment by chrisguttandin** [comment]
The number of channels and the sample rate is determined by the `MediaStream` that you record. At least that's how it should be. If you experience something different it's probably a bug.

There is currently no way to define the bit depth. Luckily it's hardcoded to 16 bit.

Does this answer your question?

**Comment by chrisguttandin** [comment]
I'm closing this since I recently added a description on how to change the `sampleRate` as part of #674.

There is already already another issue (#643) which tracks the missing `audioBitsPerSecond` option.
