### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by aquorio15** [chrisguttandin/extendable-media-recorder#661]
I am trying to record wav files but i am facing an error "Blob is not defined"
**app.js**
<img width="625" alt="Screenshot 2022-03-25 233100" src="https://user-images.githubusercontent.com/91369740/160176465-58360ed4-0d38-4a3a-a5a1-6e1dc56294f7.png">
**html file**
<img width="585" alt="Screenshot 2022-03-25 233248" src="https://user-images.githubusercontent.com/91369740/160176691-1d71f0b0-5717-44c9-8d12-ab3471e5694e.png">

**Comment by aquorio15** [comment]
**error**
<img width="1127" alt="Screenshot 2022-03-25 234556" src="https://user-images.githubusercontent.com/91369740/160178518-2e268838-7c6b-49c3-8569-47181541a686.png">

**Comment by chrisguttandin** [comment]
Hi @aquorio15, using this package with Node.js is not supported. It's not only the `Blob` that is missing. There is also no `MediaRecorder`, no `MediaStream` and no Web Audio API in Node.js.

I'll hope you find an alternative that works with Node.js.
