### ISSUE TITLE
Does this work on iOS/Mac Safari?

### ISSUE THREAD

**Issue by seebham** [chrisguttandin/extendable-media-recorder#668]
I'm trying to find an Audio recording solution that will work on all browsers and OS. Most of the available options are not working on Safari.

Can anyone confirm whether this works on Safari or not?
I really appreciate any help you can provide.

**Comment by chrisguttandin** [comment]
Hi @seebham,

Safari is one of the supported browsers. The last bug that I'm aware of is this one (chrisguttandin/extendable-media-recorder-wav-encoder#400) and it seems to be fixed.

So the short answer is 'Yes'.

Please feel free to report any bugs that you notice.
