### ISSUE TITLE
Server Error ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by Nam6201** [chrisguttandin/extendable-media-recorder#671]
import { MediaRecorderAudio } from "extendable-media-recorder"
//////////
async function requestRecorder() {
  const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  const options = { mimeType: "audio/wav" };
  
 const recorder = new MediaRecorderAudio(stream, options);
  console.log(recorder.mimeType)
  return recorder
}

![image](https://user-images.githubusercontent.com/92089773/208276269-2d811e44-a3a6-4d89-bbad-4c242b862927.png)

This is my code, it doesn't work due to the Blob error, but i don't understand where these problems come from?

**Comment by chrisguttandin** [comment]
Hi @Nam6201,

I suspect you run the code with Node.js. This library is meant to run in the browser. Unfortunately it's not possible to use it with Node.js.

**Comment by Nam6201** [comment]
Actually, my project is based on NextJs, after searching some similar issues on Google and StackOverflow, i realized this error came from NextJs syntax, so i changed my component from normal import to dynamic import and it worked. Finally, i wanna say thanks for your answer and your recorder packaged, it helped me a lot in my project. <3 <3 <3

**Comment by chrisguttandin** [comment]
Great, I'm happy to hear that. 🎉
