### ISSUE TITLE
Want to set sample rate from 48khz to 16khz. 

### ISSUE THREAD

**Issue by VijayDhake** [chrisguttandin/extendable-media-recorder#674]
We are facing audio signal drop out issue in audio recording in chrome browser. But after using [extendable-media-recorder] that issue resolved. Thanks for it. But recorded audio is of 48khz but we want 16khz. Is there any way to set it. Please let me know. Thanks in advance.

**Comment by chrisguttandin** [comment]
Hi @VijayDhake,

there is no way to do this directly with a `MediaRecorder`. But it gets asked quite frequently and therefore I've added a section to the [README](https://github.com/chrisguttandin/extendable-media-recorder#setting-the-sample-rate) which describes how it can be done with an `AudioContext`. I hope this helps.

**Comment by chrisguttandin** [comment]
Thanks for making me aware of the typo. I've fixed the readme. https://github.com/chrisguttandin/extendable-media-recorder/commit/66b9451cd14384dd66902c8f014f30928c954100

> I have tried many ways to change it but it is not changing.

What exactly did you try and didn't work?

I think setting the `channelCount` of the `MediaStreamAudioDestinationNode` should work.

```js
const mediaStreamAudioDestinationNode = new MediaStreamAudioDestinationNode(
    audioContext,
    {
        channelCount: 1
    }
);
```

**Comment by VijayDhake** [comment]
```
        let stream = await navigator.mediaDevices.getUserMedia({ audio: true });

            gumStream = stream;

          const audioContext = new AudioContext({ sampleRate: 16000 });    
          const mediaStreamAudioSourceNode = new MediaStreamAudioSourceNode(audioContext, { mediaStream: stream });
          //console.log("mediaStreamAudioSourceNode", mediaStreamAudioSourceNode)

          const mediaStreamAudioDestinationNode = new MediaStreamAudioDestinationNode(audioContext);
          //console.log("mediaStreamAudioDestinationNode", mediaStreamAudioDestinationNode)

          mediaStreamAudioSourceNode.connect(mediaStreamAudioDestinationNode);

          recorder = new MediaRecorder(mediaStreamAudioDestinationNode.stream, { mimeType: 'audio/wav', 
![console](https://user-images.githubusercontent.com/67089587/224911251-d1356bb1-61bf-4072-906b-03ee57325ac1.png)
![mediainfo](https://user-images.githubusercontent.com/67089587/224911260-f3afe7f0-2f47-4916-8489-fb94ba16bd3a.png)
channelCount: 1 });


          recorder.start();
```
Have already added and tried above solution. But Still output showing 2 channel. Attached screenshot of output.
