### ISSUE TITLE
Unresolved Import Warnings after Package Update

### ISSUE THREAD

**Issue by Scan0815** [chrisguttandin/extendable-media-recorder#678]
After updating the packages in my project, I encountered multiple unresolved import warnings during the bundling process. These imports were working correctly in previous versions. Specifically, version 5.0.7 of multi-buffer-data-view, version 5.0.7 of fast-unique-numbers, version 6.0.7 of automation-events, and version 11.0.7 of compilerr were imported without any issues. Here's a detailed list of the warnings:

```
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'multi-buffer-data-view' is imported by
           ./node_modules/extendable-media-recorder/build/es2019/factories/webm-pcm-media-recorder.js, but could not be
           resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'fast-unique-numbers' is imported by ./node_modules/broker-factory/build/es2019/module.js, but could not be
           resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'fast-unique-numbers' is imported by ./node_modules/media-encoder-host-broker/build/es2019/module.js, but
           could not be resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'fast-unique-numbers' is imported by ./node_modules/recorder-audio-worklet/build/es2019/module.js, but could
           not be resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'automation-events' is imported by ./node_modules/standardized-audio-context/build/es2019/module.js, but
           could not be resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'automation-events' is imported by
           ./node_modules/standardized-audio-context/build/es2019/factories/audio-param-factory.js, but could not be
           resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'fast-unique-numbers' is imported by
           ./node_modules/worker-factory/build/es2019/helpers/extend-worker-implementation.js, but could not be
           resolved – treating it as an external dependency.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'compilerr' is imported by ./node_modules/worker-factory/build/es2019/helpers/error-renderers.js, but could
           not be resolved – treating it as an external dependency.
```

Steps to Reproduce:

Clone the repository from [github/extendable-media-recorder-bug](https://github.com/Scan0815/extendable-media-recorder-bug)
Install the dependencies using npm install.
Run the bundling process npm start.
Observe the above warnings.
Expected Behavior: All imports should be resolved without any warnings.

Actual Behavior: Multiple unresolved import warnings are shown during the bundling process.

Additional Information:

The previous version of the packages did not exhibit this behavior.
No changes were made to the codebase apart from the package updates.
Please let me know if any further details or clarifications are needed.

**Comment by chrisguttandin** [comment]
Thanks a lot for reporting this. There was an error in the build script of those projects. I published fix for all these modules earlier today.

Re-installing the packages fixes the bug in your test case:

```sh
npm un extendable-media-recorder extendable-media-recorder-wav-encoder
npm i extendable-media-recorder extendable-media-recorder-wav-encoder
```
