### ISSUE TITLE
Get audio as pcm_s16le

### ISSUE THREAD

**Issue by ma-elation** [chrisguttandin/extendable-media-recorder#681]
Hello, I need to get the data as pcm_s16le for sending to an API.  Can you please share how to do this?

**Comment by chrisguttandin** [comment]
Hi @ma-elation,

the cleanest solution would probably be to write your own encoder similar to the existing [extendable-media-recorder-wav-encoder](https://github.com/chrisguttandin/extendable-media-recorder-wav-encoder).

But you could also re-use the wav-encoder and skip the first 44 bytes. All that is left ist the PCM data as signed 16 bit little endian integers.

**Comment by ramiel** [comment]
@ma-elation have you done this?
