### ISSUE TITLE
recording sometimes introduces slight, temporary pitch shift?

### ISSUE THREAD

**Issue by gregsadetsky** [chrisguttandin/extendable-media-recorder#682]
I am using extendable-media-recorder with extendable-media-recorder-wav-encoder -- thanks for these amazing libraries!

in one occurrence (see example .wav below), someone reported that a recording they made on my site (where I use these libraries) had a slight pitch shift during the record. it doesn't last very long (about a second) but is pretty audible.

[pitch-shift-example.wav.zip](https://github.com/chrisguttandin/extendable-media-recorder/files/13602341/pitch-shift-example.wav.zip)

is this a known problem? I didn't find anything in the closed issues. is it possible that the media recording API will sometimes skip/miss some samples, and thus will "compress" the time and thus pitch shift the signal..?

I'm using Howler as the frontend media playing library.

thank you!

**Comment by gregsadetsky** [comment]
thank you for looking into this!

the sound being recorded was coming from Howler -- I did:

```typescript
  let streamDest = Howler.ctx.createMediaStreamDestination();
  Howler.masterGain.connect(streamDest); // connect masterGain to destination

  // set up media recorder to record output
  let chunks = [];
  mediaRecorder = new MediaRecorder(streamDest.stream, {
    mimeType: "audio/wav",
  });
```

in the recording that was shared with me, the pitch shift started after 57 seconds. I don't have information re: which browser -- I'll ask and report back. I'm afraid that this issue might not be easy to reproduce, right..? thanks again!

**Comment by chrisguttandin** [comment]
Ah, that's interesting. I'm currently working on an improved mechanism to record in Safari. Up to now an AudioWorklet is used internally. That means extendable-media-recorder manages an AudioContext internally, too. My gut feeling is that the AudioContext from Howler and the one from extendable-media-recorder may drift slightly over time and the browser tries to compensate for that by resampling the audio.

The problem I'm trying to solve with the improved mechanism is that Safari sometimes inserts silence.  I ran countless tests while working on that. But I never experienced the pitch shift bug myself. Is that something that always appears for that user or was it a one time problem?

**Comment by gregsadetsky** [comment]
thanks again for looking into it / thinking about this issue! it was a one time problem so ... obviously difficult to diagnose / reproduce. I haven't heard from other people regarding this issue.

**Comment by chrisguttandin** [comment]
Okay, I will close it for now. Please feel free to open it again if you come across a way to reproduce it.
